baseURL = 'https://g-bar.github.io/'
defaultContentLanguage = 'en'
locale = 'en-US'
title = 'Gil Barrios'
theme = 'hermit-v2'
enableEmoji = true
rssLimit = 10

[security]
  [security.http]
    urls = ['(?i)^https?://[a-z0-9]', '! ^https?://\d+\.', '! (?i)^https?://[^/?#]*@']

[params]
  description = 'Designer & front-end developer building calm, intentional digital experiences.'
  homeSubtitle = 'Senior Full-stack Developer'
  homeSubtitlePrinter = true
  themeColor = '#494f5c'
  accentColor = '#018472'
  scrollToTop = true
  code_copy_button = true
  justifyContent = false
  footerHideThemeName = false

  [params.author]
    name = 'Gil Barrios'

  [[params.socialLinks]]
    name = 'github'
    url = 'https://github.com/g-bar/'

  [[params.socialLinks]]
    name = 'linkedin'
    url = 'https://www.linkedin.com/in/gil-arturo-b-377a47156/'

  [[params.socialLinks]]
    name = 'email'
    url = 'mailto:gbarv2@gmail.com'

[taxonomies]
  tag = 'tags'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = 'Technical & Architectural Excellence'
  url = 'technical-excellence/'
  weight = 1

[[menu.main]]
  name = 'Projects'
  url = 'projects/'
  weight = 2

[[menu.main]]
  name = 'About'
  url = 'about/'
  weight = 3

[[menu.main]]
  name = 'Contact'
  url = 'contact/'
  weight = 4
